### ISSUE TITLE
Google bloque les requêtes

### ISSUE THREAD

**Issue by jerrywham-pluxml5-2** [broncowdd/googol#26]
![googol-boque](https://f.cloud.github.com/assets/5592325/1531700/d30d08ee-4c6a-11e3-9eed-2c853bbde595.png)

**Comment by IPv777** [comment]
Hello,

excusez moi pour le big up de 4 ans, mais l'idée est-elle toujours d'actualité? :)

Merci d'avance

**Comment by broncowdd** [comment]
On en est au même point ^^
Cette année, Bozon m'a pris le peu de temps de prog dont je dispose

**Comment by IPv777** [comment]
Via  Github, peux-tu voir le taux d'utilisation (de cloning) de googol?
Ce serait intéressant, mais que si un bon nombre de personnes l'utilisent...

**Comment by jerrywham** [comment]
Tu peux clôturer l'issue.
