### ISSUE TITLE
Recherche d'images renvoi erreur

### ISSUE THREAD

**Issue by emporeso2** [broncowdd/googol#34]
Bonjour,

la recherche d'images me donne cette erreur : 

> Warning: file_get_contents(contenu.txt): failed to open stream: No such file or directory in xxxxxx/index.php on line 230

Parcontre la recherche video fonctionne tres bien !

**Comment by broncowdd** [comment]
oops, my bad: une ligne pour le debug qui est passée en «prod» ^^ je corrige de suite, merci ^^

**Comment by broncowdd** [comment]
Je ne vois pas la ligne dans le code... as-tu essayé avec la dernière version ?

**Comment by emporeso2** [comment]
Myyyyy bad ! 
En effet ca marche tres bien avec la derniere version.

Un tres gros merci pour ton outil et les autres aussi .
