### ISSUE TITLE
Variable indéfinie

### ISSUE THREAD

**Issue by Chouchen** [broncowdd/googol#36]
https://github.com/broncowdd/googol/blob/52e5396e537d8d991608430dcd4cfb758f5ebf3c/index.php#L41

`$bangs` n'est pas définie à ce niveau non ?

**Comment by broncowdd** [comment]
tout-à-fait pertinent ! (ça sent les mouvements de code et les copier-coller sauvages, ça ^^)
Je corrige, merci !
