### ISSUE TITLE
Redirection vers une autre instance

### ISSUE THREAD

**Issue by jerrywham** [broncowdd/googol#40]
Salut,

Tu as mis en place une redirection vers d'autres instances de googol depuis ton site lorsqu'il est surchargé.
Je ne sais pas trop comment tu t'y es pris et quelles règles tu as mis en place, mais la pluspart du temps, les instances vers lesquelles on est redirigées ne sont pas à jour.

Du coup, on n'a aucun résultat.

Serait-il possible de vérifier la version de googol utilisée par les différentes instances avant redirection ?
Si tu utilises un tableau comme bdd des instances, peut-être qu'il faudrait ajouter la version ?

**Comment by jerrywham** [comment]
En fait, je pense que c'est le dépot github qui n'est pas à jour.
Je viens de télécharger la dernière version, et je n'ai aucun résultat alors que sur ton instance, si.

T'aurais pas oublier quelque chose ? Ça serait étonnant quand même :-p

**Comment by umanu** [comment]
Bonjour,

Depuis une dixaine de jours et sans toucher à mon instance, je n'ai plus aucun résultat.

**Comment by jerrywham** [comment]
Allo Bronco, t'es là ?

**Comment by broncowdd** [comment]
C'est pour ça que j'avais testé une redirection vers d'autres instances quand la notre était bannie.
Bien entendu, il faudrait que les instances soient plus nombreuses pour que ce soit efficace...

**Comment by broncowdd** [comment]
C'est l'IP du serveur qui envoie la requête qui est bannie...

Il est impossible de remplir, depuis l'IP du serveur, le captcha de 
vérification envoyé par Google . Du coup, il faut suspendre 
temporairement les requêtes le temps d'être «débanni» ^^


Le 30/05/2018 à 10:25, umanu a écrit :

**Comment by jerrywham** [comment]
Et où qu'il est le captcha ? Quand je vais sur google.fr, j'en vois pas...

**Comment by broncowdd** [comment]
En fait, googol envoie ta recherche à google.fr, récupère la page, la 
parse pour récupérer les infos et recrée une page propre et sans traçage 
ou pub.

Le problème, c'est que si google.fr reçoit trop de requêtes depuis la 
même IP, il considère que ce n'est pas un utilisateur mais un robot et 
envoie une page contenant le captcha à remplir à la place de la page 
contenant les résultats: or, cette page est reçue par googol (et pas par 
ton navigateur); comme il ne trouve aucune info, il dit qu'il n'y a pas 
de résultats.


Le souci, c'est que même si googol te fournissait la page captcha, ça ne 
servirait à rien puisque l'IP serait la tienne et pas celle du serveur 
hébergeant googol...

Dead end.


La seule solution que j'avais trouvé c'était de rediriger vers un autre 
moteur de recherche ou une autre instance de googol le temps d'être 
unban: toutefois, il faudrait un réseau de googol plus important pour 
diluer le nombre de requêtes globales.



Le 01/06/2018 à 02:09, jerrywham a écrit :

**Comment by jerrywham** [comment]
En fait, google renvoie une erreur 301 disant que le résultat a été déplacé, en donnant une adresse en google.com.
Je te propose de modifier la fonction file_cule_contents comme suit :
```php
function file_curl_contents($url,$pretend=true,$pretendbis=false){
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept-Charset: UTF-8'));
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER,  FALSE);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_URL, $url);
		if (!ini_get("safe_mode") && !ini_get('open_basedir') ) {curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);}
		curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
		if ($pretend){curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Linux; Android 4.4.2; Che2-L11 Build/HonorChe2-L11) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36');}
    
		curl_setopt($ch, CURLOPT_REFERER, random_referer());// notez le referer "custom"

		$data = curl_exec($ch);
		$response_headers = curl_getinfo($ch);

		// Google seems to be sending ISO encoded page + htmlentities, why??
		if($response_headers['content_type'] == 'text/html; charset=ISO-8859-1') $data = html_entity_decode(iconv('ISO-8859-1', 'UTF-8//TRANSLIT', $data)); 
		# $data = curl_exec($ch);

		curl_close($ch);

		if (strpos($data,'<HTML><HEAD>') !== false) {
			$data = trim(strip_tags(str_replace(array('amp;',"\n",'<HTML><HEAD><meta http-equiv="content-type" content="'.$response_headers['content_type'].'">','<TITLE>301 Moved</TITLE></HEAD><BODY>','<H1>301 Moved</H1>','The document has moved','<A HREF="','">here</A>.','</BODY></HTML>'),'',$data)));
			$data = file_curl_contents($data,false,true);
		}

		return $data;
	}
```

**Comment by broncowdd** [comment]
Ok, je teste ! merci copain ;-)

**Comment by umanu** [comment]
Merci
