### ISSUE TITLE
Les images pointent vers google

### ISSUE THREAD

**Issue by jerrywham** [broncowdd/googol#41]
Les images sont en background avec une url chiffrée qui pointe vers encrypted-tbn0.gstatic.com.

On continue d'être fliqué...

En plus, chez moi, elles ne s'affichent pas.

**Comment by jerrywham** [comment]
Je n'avais pas vu l'option pour ne pas utiliser les thumbs de google. Donc on n'est plus fliqués. Par contre, toujours pas d'affichage chez moi alors que la miniature est bien importée...

**Comment by jerrywham** [comment]
Bon, je n'ai rien dit. J'ai oublié le css...
Ok, je sors...

**Comment by jerrywham** [comment]
Faudrait faire une fonction de nettoyage des miniatures à intervalles réguliers histoire de ne pas exploser le serveur...

**Comment by broncowdd** [comment]
elle y est: 
session_start();
	if (isset($_GET['lang'])){$langue=strip_tags($_GET['lang']);}else{$langue=strip_tags(lang());}
	**clear_cache();// vire les thumbs de plus de trois minutes**
	define('LANGUAGE',$langue);

^^

**Comment by jerrywham** [comment]
Plouf, plouf, on dirait que vous n'avez rien lu et que j'aurais rien dit...
